<?php
/**
 * NegotiableQuoteDataNegotiableQuoteItemInterface
 *
 * PHP version 5
 *
 * @category Class
 * @package  SpringImport\Swagger\Magento2\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Commerce for B2B 2.2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SpringImport\Swagger\Magento2\Client\Model;

use \ArrayAccess;

/**
 * NegotiableQuoteDataNegotiableQuoteItemInterface Class Doc Comment
 *
 * @category    Class
 * @description Interface CompanyQuoteConfigInterface
 * @package     SpringImport\Swagger\Magento2\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NegotiableQuoteDataNegotiableQuoteItemInterface implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'negotiable-quote-data-negotiable-quote-item-interface';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'itemId' => 'int',
        'originalPrice' => 'float',
        'originalTaxAmount' => 'float',
        'originalDiscountAmount' => 'float',
        'extensionAttributes' => '\SpringImport\Swagger\Magento2\Client\Model\NegotiableQuoteDataNegotiableQuoteItemExtensionInterface'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'itemId' => 'item_id',
        'originalPrice' => 'original_price',
        'originalTaxAmount' => 'original_tax_amount',
        'originalDiscountAmount' => 'original_discount_amount',
        'extensionAttributes' => 'extension_attributes'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'itemId' => 'setItemId',
        'originalPrice' => 'setOriginalPrice',
        'originalTaxAmount' => 'setOriginalTaxAmount',
        'originalDiscountAmount' => 'setOriginalDiscountAmount',
        'extensionAttributes' => 'setExtensionAttributes'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'itemId' => 'getItemId',
        'originalPrice' => 'getOriginalPrice',
        'originalTaxAmount' => 'getOriginalTaxAmount',
        'originalDiscountAmount' => 'getOriginalDiscountAmount',
        'extensionAttributes' => 'getExtensionAttributes'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['itemId'] = isset($data['itemId']) ? $data['itemId'] : null;
        $this->container['originalPrice'] = isset($data['originalPrice']) ? $data['originalPrice'] : null;
        $this->container['originalTaxAmount'] = isset($data['originalTaxAmount']) ? $data['originalTaxAmount'] : null;
        $this->container['originalDiscountAmount'] = isset($data['originalDiscountAmount']) ? $data['originalDiscountAmount'] : null;
        $this->container['extensionAttributes'] = isset($data['extensionAttributes']) ? $data['extensionAttributes'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['itemId'] === null) {
            $invalid_properties[] = "'itemId' can't be null";
        }
        if ($this->container['originalPrice'] === null) {
            $invalid_properties[] = "'originalPrice' can't be null";
        }
        if ($this->container['originalTaxAmount'] === null) {
            $invalid_properties[] = "'originalTaxAmount' can't be null";
        }
        if ($this->container['originalDiscountAmount'] === null) {
            $invalid_properties[] = "'originalDiscountAmount' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['itemId'] === null) {
            return false;
        }
        if ($this->container['originalPrice'] === null) {
            return false;
        }
        if ($this->container['originalTaxAmount'] === null) {
            return false;
        }
        if ($this->container['originalDiscountAmount'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets itemId
     * @return int
     */
    public function getItemId()
    {
        return $this->container['itemId'];
    }

    /**
     * Sets itemId
     * @param int $itemId Quote item id
     * @return $this
     */
    public function setItemId($itemId)
    {
        $this->container['itemId'] = $itemId;

        return $this;
    }

    /**
     * Gets originalPrice
     * @return float
     */
    public function getOriginalPrice()
    {
        return $this->container['originalPrice'];
    }

    /**
     * Sets originalPrice
     * @param float $originalPrice Quote item original price
     * @return $this
     */
    public function setOriginalPrice($originalPrice)
    {
        $this->container['originalPrice'] = $originalPrice;

        return $this;
    }

    /**
     * Gets originalTaxAmount
     * @return float
     */
    public function getOriginalTaxAmount()
    {
        return $this->container['originalTaxAmount'];
    }

    /**
     * Sets originalTaxAmount
     * @param float $originalTaxAmount Quote item original tax amount
     * @return $this
     */
    public function setOriginalTaxAmount($originalTaxAmount)
    {
        $this->container['originalTaxAmount'] = $originalTaxAmount;

        return $this;
    }

    /**
     * Gets originalDiscountAmount
     * @return float
     */
    public function getOriginalDiscountAmount()
    {
        return $this->container['originalDiscountAmount'];
    }

    /**
     * Sets originalDiscountAmount
     * @param float $originalDiscountAmount Quote item original discount amount
     * @return $this
     */
    public function setOriginalDiscountAmount($originalDiscountAmount)
    {
        $this->container['originalDiscountAmount'] = $originalDiscountAmount;

        return $this;
    }

    /**
     * Gets extensionAttributes
     * @return \SpringImport\Swagger\Magento2\Client\Model\NegotiableQuoteDataNegotiableQuoteItemExtensionInterface
     */
    public function getExtensionAttributes()
    {
        return $this->container['extensionAttributes'];
    }

    /**
     * Sets extensionAttributes
     * @param \SpringImport\Swagger\Magento2\Client\Model\NegotiableQuoteDataNegotiableQuoteItemExtensionInterface $extensionAttributes
     * @return $this
     */
    public function setExtensionAttributes($extensionAttributes)
    {
        $this->container['extensionAttributes'] = $extensionAttributes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\SpringImport\Swagger\Magento2\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\SpringImport\Swagger\Magento2\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


