<?php
/**
 * SharedCatalogDataSharedCatalogInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SpringImport\Swagger\Magento2\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Commerce for B2B 2.2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SpringImport\Swagger\Magento2\Client;

/**
 * SharedCatalogDataSharedCatalogInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description SharedCatalogInterface interface.
/**
 * @package     SpringImport\Swagger\Magento2\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SharedCatalogDataSharedCatalogInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SharedCatalogDataSharedCatalogInterface"
     */
    public function testSharedCatalogDataSharedCatalogInterface()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "customerGroupId"
     */
    public function testPropertyCustomerGroupId()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "createdBy"
     */
    public function testPropertyCreatedBy()
    {

    }

    /**
     * Test attribute "storeId"
     */
    public function testPropertyStoreId()
    {

    }

    /**
     * Test attribute "taxClassId"
     */
    public function testPropertyTaxClassId()
    {

    }

}
